server:
  port: 8081
spring:
  application:
    name: kafka-consumer
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: slow.kafka.consumer.util.XmlDeserializer

logging:
  level:
    #org.springframework.kafka: DEBUG
    #org.apache.kafka.clients: DEBUG
    slow.kafka.consumer: DEBUG
    root: INFO